### ISSUE TITLE
Ajustes a sitio de php

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/projects-se-ui#104]
# Descripción y resultado

Agrupar los issues de bon-in-a-box para tenerlos en cuenta en la carga de Manuel y hacer seguimiento al trabajo realizado.

- [ ] Liked projects should appear in favorites dropdown and in the favorites section of the dashboard: https://github.com/GEO-BON/bon-in-a-box/issues/88
- [x] Project card pictures load slowly: https://github.com/GEO-BON/bon-in-a-box/issues/93
- [x] PHP errors in project creation: https://github.com/GEO-BON/bon-in-a-box/issues/95

**Comment by ManuelStardust** [comment]
Se generaron los siguientes pull request:
- [Carga de imágenes](https://github.com/GEO-BON/bon-in-a-box/pull/103)
- [Error en creación de proyectos](https://github.com/GEO-BON/bon-in-a-box/pull/102)

**Comment by erikasv** [comment]
El PR del primer punto quedó abierto, pendiente de revisión por parte de Jean-Michel, se cierra esta tarea porque Manuel ya no estará trabajando más en este proyecto.
